### ISSUE TITLE
Footer enhancement

### ISSUE THREAD

**Issue by Aneeshaik** [Anu27n/603work#72]
![image](https://github.com/user-attachments/assets/eab3211a-d76b-49c4-8c1c-7e9f647610a3)
The names which are placed at the left and right side of the subscription card are not much visible. I would like to place left potion above to the logo inside the card and right portion at the bottom of the card. Instead of adding names of the social media platforms I would like to add logo's of every platform and write "Follow us on" like text. I can do it better. Please assign me to this task under hacktoberfest. Thank you!

**Comment by Anu27n** [comment]
@Aneeshaik Assigned

**Comment by Anu27n** [comment]
@Aneeshaik  Check if Using the Correct Account
Make sure that Aneeshaik is logged into the correct GitHub account in the terminal or command line. If they have multiple GitHub accounts, they might be using the wrong credentials.

To Check Current Git Config:

bash
Copy code
git config --global user.name
git config --global user.email
If these are incorrect, update them with:

bash
Copy code
git config --global user.name "Aneeshaik"
git config --global user.email "aneeshaik@example.com"
3. Clear Cached Credentials
If the credentials are cached incorrectly, clearing them might help:

On macOS:

bash
Copy code
git credential-osxkeychain erase
On Windows: Open Credential Manager and remove any GitHub credentials.

On Linux: You might have to clear them manually from the ~/.git-credentials file.

4. Use SSH Instead of HTTPS
If you have SSH access set up, consider switching to SSH instead of HTTPS to push code.

Switch to SSH:
Ensure that you have an SSH key set up. You can check this with:

bash
Copy code
ls -al ~/.ssh
You should see a file like id_rsa and id_rsa.pub. If not, you can generate one using:

bash
Copy code
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
Add the SSH key to your GitHub account by copying the content of id_rsa.pub to your GitHub SSH settings.

Change the remote URL of your repository to use SSH:

bash
Copy code
git remote set-url origin git@github.com:Anu27n/603work.git
5. Retry the Push Command
After granting access or resolving any credential issues, try pushing your changes again:

bash
Copy code
git push origin anees
Conclusion
If Aneeshaik is still unable to push after following these steps, double-check that the user was correctly added to the repository and that there are no organizational policies or branch protection rules preventing them from pushing. Let me know if you need further assistance!

**Comment by Anu27n** [comment]
@Aneeshaik bro anyone can access it, i thing there is issue from ur side

**Comment by Aneeshaik** [comment]
hello @Anu27n , it's keeps showing like this 
` git push origin anees
ERROR: Permission to Anu27n/603work.git denied to Aneeshaik.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
